# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Appostolic' do
  pod 'RestKit', '~> 0.25.0'
  pod 'GradientView'
  pod 'DTCoreText'
end

target 'AppostolicTests' do

end

target 'AppostolicUITests' do

end

